---
version: '3'
services:
  tests:
    image: buildkite/plugin-tester:latest
    volumes:
      - .:/plugin
  lint:
    image: buildkite/plugin-linter:latest
    command: ['--id', 'heap/monorepo-diff']
    volumes:
      - ".:/plugin"